"""added default user in user_table

Revision ID: 45d5291a2cb4
Revises: 911524cdbc3d
Create Date: 2025-02-20 21:17:49.305039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d5291a2cb4'
down_revision: Union[str, None] = '911524cdbc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('admin', 'user', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
